language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: docs
      script:
        - npm ci
        - npm run docz:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
        local-dir: .docz/dist
        on:
          branch: master
