const plugins = require('.');

module.exports = {
  theme: {
    grid: {
      columns: 12,
    },
    screens: {
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
    },
    fontWeights: {
      400: 400,
      500: 500,
      600: 600,
      700: 700,
    },
    lineHeight: {
      0: 0,
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
    width: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vw',
    }),
  },
  variants: {
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    fontStyle: [],
    height: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    overflow: [],
    position: [],
    width: [],
    zIndex: [],
  },
  corePlugins: [
    'alignContent',
    'alignItems',
    'alignSelf',
    'display',
    'flex',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'fontStyle',
    'height',
    'justifyContent',
    'letterSpacing',
    'lineHeight',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'overflow',
    'position',
    'width',
    'zIndex',
  ],
  plugins,
  options: {
    prefix: '',
    important: false,
    separator: ':',
  },
};
