const plugins = require('./');

module.exports = {
  theme: {
    grid: {
      columns: 12,
    },
    screens: {
      sm: '576px',
      md: '768px',
      lg: '992px',
      xl: '1200px',
    },
    fontWeights: {
      4: 400,
      7: 700,
    },
    leading: {
      none: 1,
      tight: 1.25,
      normal: 1.5,
      loose: 2,
    },
    borderRadius: {
      0: '0',
      1: '.125rem',
      2: '.25rem',
      3: '.5rem',
      4: '1rem',
      pill: '9999px',
    },
    width: {
      auto: 'auto',
      4: '1rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
      16: '4rem',
      24: '6rem',
      32: '8rem',
      48: '12rem',
      64: '16rem',
      full: '100%',
    },
    height: {
      auto: 'auto',
      4: '1rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
      16: '4rem',
      24: '6rem',
      32: '8rem',
      48: '12rem',
      64: '16rem',
      full: '100%',
      screen: '100vh'
    },
    minWidth: {
      0: '0',
      full: '100%',
    },
    minHeight: {
      0: '0',
      full: '100%',
      screen: '100vh'
    },
    maxWidth: {
      xs: '20rem',
      sm: '30rem',
      md: '40rem',
      lg: '50rem',
      xl: '60rem',
      full: '100%',
    },
    maxHeight: {
      full: '100%',
      screen: '100vh',
    },
    spacing: {
      auto: 'auto',
      0: '0',
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      6: '1.5rem',
      8: '2rem',
      12: '3rem',
    },
    zIndex: {
      0: 0,
      1: 1,
      2: 2,
    },
    opacity: {
      0: '0',
      100: '1',
    },
  },
  variants: {
    flexDirection: [],
    flexWrap: [],
    alignItems: [],
    alignContent: [],
    alignSelf: [],
    justifyContent: [],
    flex: [],
    flexGrow: [],
    flexShrink: [],
    height: [],
    lineHeight: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    overflow: [],
    position: [],
    letterSpacing: [],
    width: [],
    zIndex: [],
  },
  corePlugins: [
    'display',
    'flexDirection',
    'flexWrap',
    'alignItems',
    'alignContent',
    'alignSelf',
    'justifyContent',
    'flex',
    'flexGrow',
    'flexShrink',
    'height',
    'lineHeight',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'overflow',
    'position',
    'letterSpacing',
    'width',
    'zIndex',
  ],
  plugins,
  options: {
    prefix: '',
    important: false,
    separator: ':',
  },
}
